const MEN_BMR_CONSTANTS = {
  BASE_METABOLIC_RATE: 88.362,
  WEIGHT_COEFFICIENT: 13.397,
  HEIGHT_COEFFICIENT: 4.799,
  AGE_COEFFICIENT: 5.677,
};

const WOMEN_BMR_CONSTANTS = {
  BASE_METABOLIC_RATE: 447.593,
  WEIGHT_COEFFICIENT: 9.247,
  HEIGHT_COEFFICIENT: 3.098,
  AGE_COEFFICIENT: 4.33,
};

module.exports = {
  MEN_BMR_CONSTANTS,
  WOMEN_BMR_CONSTANTS,
};
