const BASE_WATER_REQUIREMENT_COEFFICIENT = 0.03;

const MINIMAL_ACTIVITY_COEFFICIENT = 0;
const LIGHT_ACTIVITY_COEFFICIENT = 0.35;
const AVERAGE_ACTIVITY_COEFFICIENT = 0.35;
const HIGH_ACTIVITY_COEFFICIENT = 0.35;
const VERY_HIGH_ACTIVITY_COEFFICIENT = 0.7;

module.exports = {
  BASE_WATER_REQUIREMENT_COEFFICIENT,
  MINIMAL_ACTIVITY_COEFFICIENT,
  LIGHT_ACTIVITY_COEFFICIENT,
  AVERAGE_ACTIVITY_COEFFICIENT,
  HIGH_ACTIVITY_COEFFICIENT,
  VERY_HIGH_ACTIVITY_COEFFICIENT,
};
